site_name: –î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è Muri
site_url: https://muri-docs.gizuhub.ru
copyright: "&copy; 2024 Muri. –í—Å–µ –ø—Ä–∞–≤–∞ –∑–∞—â–∏—â–µ–Ω—ã"
site_description: –î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è –¥–ª—è Discord –±–æ—Ç–∞ Muri –∏ –µ–≥–æ API

theme:
  name: material
  language: ru
  custom_dir: overrides
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.top
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: –ü–µ—Ä–µ–∫–ª—é—á–∏—Ç—å –Ω–∞ —Å–≤–µ—Ç–ª—É—é —Ç–µ–º—É

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      accent: teal
      scheme: default
      toggle:
        icon: material/brightness-7
        name: –ü–µ—Ä–µ–∫–ª—é—á–∏—Ç—å –Ω–∞ —Ç–µ–º–Ω—É—é —Ç–µ–º—É

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: –ü–µ—Ä–µ–∫–ª—é—á–∏—Ç—å –Ω–∞ —Å–∏—Å—Ç–µ–º–Ω—É—é —Ç–µ–º—É

plugins:
  - offline
  - search
  - social:
      cards_layout_options:
        background_color: teal

extra:
  generator: false
  consent:
    title: –ú—ã –∏—Å–ø–æ–ª—å–∑—É–µ–º –ø–µ—á–µ–Ω—å–∫–∏ üç™
    description: >-
      –ú—ã –∏—Å–ø–æ–ª—å–∑—É–µ–º cookie –∏ –∞–Ω–∞–ª–∏—Ç–∏–∫—É –¥–ª—è —É–ª—É—á—à–µ–Ω–∏—è –≤–∑–∞–∏–º–æ–¥–µ–π—Å—Ç–≤–∏—è —Å –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏–µ–π.
    actions:
      - accept
      - reject
  analytics:
    provider: google
    property: G-RJJ9WZVGD6
    feedback:
      title: –°—Ç—Ä–∞–Ω–∏—Ü–∞ –±—ã–ª–∞ –ø–æ–ª–µ–∑–Ω–æ–π?
      ratings:
        - icon: material/emoticon-happy-outline
          name: –°—Ç—Ä–∞–Ω–∏—Ü–∞ –±—ã–ª–∞ –ø–æ–ª–µ–∑–Ω–æ–π
          data: 1
          note: >-
            –°–ø–∞—Å–∏–±–æ –∑–∞ –æ–±—Ä–∞—Ç–Ω—É—é —Å–≤—è–∑—å!
        - icon: material/emoticon-sad-outline
          name: –õ—É—á—à–µ –±—ã —É–ª—É—á—à–∏—Ç—å —Å—Ç—Ä–∞–Ω–∏—Ü—É
          data: 0
          note: >-
            –°–ø–∞—Å–∏–±–æ –∑–∞ –æ–±—Ä–∞—Ç–Ω—É—é —Å–≤—è–∑—å! –ü—Ä–∏–º–µ–º —ç—Ç–æ –≤–æ –≤–Ω–∏–º–∞–Ω–∏–µ.

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - –ì–ª–∞–≤–Ω–∞—è:
      - –î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å: index.md
      - –ö–∞–∫ –ø—Ä–∏–≥–ª–∞—Å–∏—Ç—å –±–æ—Ç–∞: invite.md
      - –ß–ê–í–û: faq.md
  - –†–∞–±–æ—Ç–∞ —Å API:
      - –î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å: api/index.md
      - –ú–µ—Ç–æ–¥—ã:
          - GET /v1/booru: api/methods/get-booru.md
      - –û–±—ä–µ–∫—Ç—ã:
          - BooruPost: api/objects/booru-post.md
          - BooruFile: api/objects/booru-file.md
  - –ü—Ä–∞–≤–æ–≤–∞—è –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è:
      - –£—Å–ª–æ–≤–∏—è –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è: legal/terms.md
      - –ü–æ–ª–∏—Ç–∏–∫–∞ –∫–æ–Ω—Ñ–∏–¥–µ–Ω—Ü–∏–∞–ª—å–Ω–æ—Å—Ç–∏: legal/privacy.md
      - –ü—É–±–ª–∏—á–Ω–∞—è –æ—Ñ–µ—Ä—Ç–∞: legal/oferta.md
  - –°–ø–∏—Å–æ–∫ –∏–∑–º–µ–Ω–µ–Ω–∏–π:
      - –¢–µ–∫—É—â–µ–µ –æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ: changelog/index.md
      - –ê—Ä—Ö–∏–≤ –æ–±–Ω–æ–≤–ª–µ–Ω–∏–π:
          - –û–±–Ω–æ–≤–ª–µ–Ω–∏–µ 0.1.7: changelog/0-1-7.md
          - –û–±–Ω–æ–≤–ª–µ–Ω–∏–µ 0.1.6: changelog/0-1-6.md
          - –û–±–Ω–æ–≤–ª–µ–Ω–∏–µ 0.1.5: changelog/0-1-5.md
          - –û–±–Ω–æ–≤–ª–µ–Ω–∏–µ 0.1.4: changelog/0-1-4.md
          - –û–±–Ω–æ–≤–ª–µ–Ω–∏–µ 0.1.3: changelog/0-1-3.md
          - –û–±–Ω–æ–≤–ª–µ–Ω–∏–µ 0.1.2: changelog/0-1-2.md
          - –û–±–Ω–æ–≤–ª–µ–Ω–∏–µ 0.1.1: changelog/0-1-1.md
  - –ü–æ–¥–¥–µ—Ä–∂–∫–∞: "https://discord.gg/edGKDHYXPb"
